apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  image: python:3.12-alpine
  command:
    - /usr/local/bin/python3
    - -m
    - http.server
    - "8080"
    - --bind
    - 0.0.0.0
  ports:
    - containerPort: 8080
      hostPort: 8091
